# Generated by Django 4.2.6 on 2024-05-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttable',
            old_name='is_avaiable',
            new_name='is_available',
        ),
        migrations.AlterField(
            model_name='producttable',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
